In [1]:
import numpy as np

In [11]:
marks = [4, 5, 4, 9, 9, 1, 1, 4, 5, 6]
n1 = np.array(marks, dtype=np.int16)
print(n1)
print(type(n1))
print(n1.ndim)
print(n1.shape)
print(n1.dtype)

[4 5 4 9 9 1 1 4 5 6]
<class 'numpy.ndarray'>
1
(10,)
int16


Add 1 pointer

In [12]:
addedmarks = n1 + 1
print(addedmarks)
print(type(addedmarks))

[ 5  6  5 10 10  2  2  5  6  7]
<class 'numpy.ndarray'>


Deduct 1 marks

In [14]:
deductedmarks = n1 - 1
print(deductedmarks)

[3 4 3 8 8 0 0 3 4 5]


Vectorized operations. Operations achieved on a vector of values without explicitly writing a loop

In [15]:
print(n1 ** 2)

[16 25 16 81 81  1  1 16 25 36]


Indexing

In [20]:
print(n1)
print(n1[0])
print(n1[-1])
print(n1[[0, -1]]) # multiple indexing

[4 5 4 9 9 1 1 4 5 6]
4
6
[4 6]


Slicing

In [27]:
print(n1)
print(n1[0:3])
print(n1[:3])
print(n1[3:])
print(n1[::2])
print(n1[-4:])

[4 5 4 9 9 1 1 4 5 6]
[4 5 4]
[4 5 4]
[9 9 1 1 4 5 6]
[4 4 9 1 5]
[1 4 5 6]


Slicing + assignment

In [30]:
print(n1)
n1[3:6] = 0
print(n1)

[4 5 4 0 0 0 1 4 5 6]
[4 5 4 0 0 0 1 4 5 6]


In [31]:
print(n1)

[4 5 4 0 0 0 1 4 5 6]


Arithemtic functions

In [38]:
print(n1.mean())
print(n1.std())
print(n1.var())
print(n1.sum())
print(n1.max())
print(n1.min())
print(n1.cumsum())

2.9
2.2561028345356955
5.090000000000001
29
6
0
[ 4  9 13 13 13 13 14 18 23 29]


In [39]:
print(n1.sort())

None


In [40]:
print(n1)

[0 0 0 1 4 4 4 5 5 6]


Filtering

In [45]:
n2 = np.array([4, 5, 10, 10, 1, 5, 6, 7, 2, 3, 3, 10])

In [46]:
n3 = n2[n2 >= 5]
print(n3)

[ 5 10 10  5  6  7 10]


In [47]:
n4 = n2[(n2 < 5) | (n2 == 10)]
print(n4)

[ 4 10 10  1  2  3  3 10]


Filtering + Assignment

In [50]:
print(n2)
n2[n2 == 10] = 0

[ 4  5 10 10  1  5  6  7  2  3  3 10]


In [53]:
print(n2)

[4 5 0 0 1 5 6 7 2 3 3 0]


In [58]:
uniquepointers, count = np.unique(n2, return_counts=True)
print(uniquepointers)
print(count)

[0 1 2 3 4 5 6 7]
[3 1 1 2 1 2 1 1]


In [61]:
print(n2)
weightedmarks = np.where(n2 > 5, 1, 0)
print(weightedmarks)

[4 5 0 0 1 5 6 7 2 3 3 0]
[0 0 0 0 0 0 1 1 0 0 0 0]
