In [1]:
import numpy as np

In [5]:
print(np.zeros(10))
print(np.ones(10))
print(np.zeros((3,3)))
print(np.identity(3))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
print(np.arange(10))
print(np.arange(4, 21))
n1 = np.arange(20)
n2 = n1.reshape(5, 4)

[0 1 2 3 4 5 6 7 8 9]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [24]:
import numpy.random as rd

In [25]:
print(rd.random(50))
print(rd.randn(3,3))

[0.92021393 0.08806622 0.68533314 0.57481079 0.8682009  0.61897474
 0.43338693 0.9222597  0.03499407 0.75547328 0.93328516 0.78787799
 0.69102576 0.66125474 0.16762255 0.82178694 0.06387757 0.85583051
 0.30152071 0.58467361 0.89046417 0.45890927 0.84290421 0.28683671
 0.61883287 0.47989182 0.60288935 0.3794887  0.29748759 0.16592715
 0.42736769 0.93017272 0.71539194 0.3782629  0.66331444 0.10714395
 0.85452343 0.54885863 0.72122912 0.38978973 0.35619015 0.0893335
 0.22231981 0.14768674 0.54391912 0.32915682 0.8634193  0.35612566
 0.85169253 0.6308045 ]
[[ 0.11267563 -0.09735897  1.02403149]
 [-1.92146699 -0.24490082 -1.44391697]
 [ 0.98416826  0.53920263 -0.6672575 ]]


In [28]:
print(n2)
n3 = np.ravel(n2)
print(n3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
