In [1]:
import numpy as np

In [4]:
pcm = [
    [67, 83, 98],
    [98, 99, 76],
    [100, 92, 89]
]
n1 = np.array(pcm)
print(n1)
print(type(n1))
print(n1.ndim)
print(n1.shape)

[[ 67  83  98]
 [ 98  99  76]
 [100  92  89]]
<class 'numpy.ndarray'>
2
(3, 3)


In [5]:
correctedmarks = n1 + [0, 1, 2]
print(correctedmarks)

[[ 67  84 100]
 [ 98 100  78]
 [100  93  91]]


In [10]:
print(n1[0])
print(n1[-1])
print(n1[-1, 2])
print(n1[0, 0])
print(n1[[0, -1]])

[67 83 98]
[100  92  89]
89
67
[[ 67  83  98]
 [100  92  89]]


In [15]:
print(n1[-2:])
print(n1[-2:, :2])
print(n1[-2:, [0, 1]])
print(n1[[0, 1], -2:])

[[ 98  99  76]
 [100  92  89]]
[[ 98  99]
 [100  92]]
[[ 98  99]
 [100  92]]
[[83 98]
 [99 76]]


In [23]:
print(n1)
print(n1.mean(axis=0))
print(n1.sum(axis=1))
print(n1[:,0].mean())
chemmaths = n1[:, -2:]
print(chemmaths.std(axis=0))

[[ 67  83  98]
 [ 98  99  76]
 [100  92  89]]
[88.33333333 91.33333333 87.66666667]
[248 273 281]
88.33333333333333
[6.5489609  9.03081146]


In [24]:
print(n1)

[[ 67  83  98]
 [ 98  99  76]
 [100  92  89]]


In [25]:
n4 = np.array([
    [45, 67, 100],
    [94, 95, 67]
])

In [26]:
consolidated = np.vstack((n1, n4))
print(consolidated)

[[ 67  83  98]
 [ 98  99  76]
 [100  92  89]
 [ 45  67 100]
 [ 94  95  67]]


In [27]:
verbalquant = np.array([
    [100, 100],
    [56, 89],
    [99, 94],
    [78, 75],
    [98, 100]
])

In [28]:
history = np.hstack((consolidated, verbalquant))
print(history)

[[ 67  83  98 100 100]
 [ 98  99  76  56  89]
 [100  92  89  99  94]
 [ 45  67 100  78  75]
 [ 94  95  67  98 100]]


In [29]:
weighted = np.where(history == 100, 1, 0)
print(weighted)

[[0 0 0 1 1]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 0 1]]
